### ISSUE TITLE
IsNotDisplayed returns NotFoundElement

### ISSUE THREAD

**Issue by priomino** [KasperskyLab/Kaspresso#118]
I tryed to write something like this:
```
          AutologinScreen {
                compose {
                    or(quickSignIn) { isNotDisplayed() }
                    or(quickSignIn) { click() }
                }
            }
```

But it returns Element not found for isNotDisplayed()

**Comment by priomino** [comment]
temporary workaround:
continuously {
                compose {
                    or(AutologinScreen.quickSignIn) { isVisible() } then {
                        AutologinScreen {
                            quickSignIn {
                                click()
                            }
                        }
                    }
                    or(OtherScreen.button1) { isVisible() }
                }
            }

**Comment by matzuk** [comment]
Hi!
Please accurate some information:
It is Kautomator or Kaspresso? On the first message, I see Kautomator (the typical error points on Kautomator). But, on the second message, I see methods from Kaspresso only (```isVisible``` doesn't exist for Kautomator, there is ```isDisplayed```).

**Comment by matzuk** [comment]
Can not reproduced
