### ISSUE TITLE
Add ability to turn off test step autonumeration.

### ISSUE THREAD

**Issue by dector** [KasperskyLab/Kaspresso#13]
For now each step is logged with generated [step number in header](https://github.com/KasperskyLab/Kaspresso/blob/4b8e10e8f3cd42858bde87da500838f74bf47d0b/kaspresso/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/testcase/impl/logging/LoggingStepWatcherInterceptor.kt#L75).

As discussed in Telegram chat, it's nice to have ability to turn off auto-numeration.

**Comment by matzuk** [comment]
#15
