### ISSUE TITLE
Поправить логи в Adb Server

### ISSUE THREAD

**Issue by RuslanMingaliev** [KasperskyLab/Kaspresso#133]
- [ ] Изменить внешний вид логов (убрать нижнее подчеркивание)

- [ ] Добавить дополнительные атрибуты (время, какой именно сервак работает, что-то еще?)

- [ ] Разделить логи на debug и verbose.
**Изначальная проблема**. Когда работает desktop.jar, на хосте есть эмулятор, но на эмуляторе не запущен kaspresso-тест (собственно соединение не установлено с desktop.jar), то со стороны desktop.jar выводятся циклические сообщения, которые мало о чем говорят простому пользователю. Плюс там присутствует циклический EOException, что не добавляет оптимизма. Как отладочная информация для разработчиков - ок, но для простых пользователей должны быть максимально адекватные логи.
**Конечная цель**. В verbose выводим обработанные и понятные простому пользователю сообщения. В debug - максимально все.
**Тестовые сценарии**. 
1. Стартовали desktop.jar, нет эмуляторов. Потом появляется эмулятор. Потом на эмуляторе запускается тест с Kaspresso, где используется AdbServer. Потом тест убивается. Затем тест снова стартует.
2. Тоже самое, только с несколькими эмуляторами, и порядок появления и уничтожения эмуляторов и тестов хаотичен.
3. Обратная ситуация, когда сначала стартует эмулятор с тестом, а потом только появляется desktop.jar (или даже несколько desktop.jar).

- [ ] Добавить в логи инфу о compatible версии desktop.jar и где её взять в случае ошибок (@RuslanMingaliev)

- [ ] Настроить публикацию desktop.jar (на @RuslanMingaliev)

**Comment by RuslanMingaliev** [comment]
@matzuk надо добавить в логи инфу о том, где брать нужную версию adb server-a. Публикацию desktop.jar-a сделаю

**Comment by matzuk** [comment]
@AzamatCherchesov попробует сделать

**Comment by matzuk** [comment]
> Добавить в логи инфу о compatible версии desktop.jar и где её взять в случае ошибок

@RuslanMingaliev можешь раскрыть, что и как тут предполагалось сделать?

**Comment by AzamatCherchesov** [comment]
По данной задаче при личной беседе были выделены следующие пункты:
1. Проверить счетчик одинаковых отладочных сообщений (вроде он был, чтоб не сломался)
2. Desktop-5060 - добавить к тегу номер порта
3. Убираем пробелы
4. Default port - определить порт, на котором работает сервер
5. EOF - проверить, что в логах не появляется EOF
6. В логах device указать desktop
7. Убрать tag на класс и метод
