### ISSUE TITLE
Util functions for WebView

### ISSUE THREAD

**Issue by priomino** [KasperskyLab/Kaspresso#155]
Need to add useful functions for working with pages.
For switching to iframe
For getting html of page or part

**Comment by priomino** [comment]
I have code, need to add

**Comment by RuslanMingaliev** [comment]
@priomino please attach a gist. I'll take a look

**Comment by priomino** [comment]
@RuslanMingaliev
here sample lines, need to think how to integrate in Kaspresso https://gist.github.com/priomino/17b5b27fb99a08337f596044813fb2e8

**Comment by Nikitae57** [comment]
Hi, @priomino ! Thank you for your samples. It looks like they have a very specific use case and we wouldn't want to include them to kaspresso. I'd suggest you to extract them to your local utils class or add them through kotlin extensions. You could create package private test methods inside your fragment or activity that interact with or expose a webview and use it in your tests
