### ISSUE TITLE
WebDriver support

### ISSUE THREAD

**Issue by priomino** [KasperskyLab/Kaspresso#156]
For some cases you can't use WebView of http clients for web. 
For that need to implement support of Selenium to adb server and add api to kaspresso. 

Simple use case: device offline

**Comment by matzuk** [comment]
Looks weird =)
I can't imagine how and for what to use WebView when a device is offline.
If you are still interested then reopen the issue and reserve a meeting.

**Comment by priomino** [comment]
I just write more info for future.
Suppose you have case:
* do some thing in app
* move device to offline
* do some checks on web site - you cant do this from inside Kaspresso, because no internet available

I don't have such test cases now. Leaving it here for reference
