### ISSUE TITLE
Обернуть проверки переключения Wi-Fi/MobileData во flakySafely [Android 8 specific]

### ISSUE THREAD

**Issue by RuslanMingaliev** [KasperskyLab/Kaspresso#166]
В некоторых случаях (заметил только на Android 8) не проходит проверка 
```kotlin
val result = adbServer.performShell(NETWORK_STATE_CHECK_CMD)
```
в `NetworkImpl`. Нужно обернуть эту проверку во flakySafely с интервалом ~50мс и ограничением в ~500мс

**Comment by matzuk** [comment]
Не забыть про:
- В wiki добавить описание про Network и особенности эмуляторов с wi-fi до 25 апи
- Со старой версией desktop.jar
`message => java.lang.ClassNotFoundException: com.kaspersky.adbserver.implementation.transferring.TaskMessage`
