### ISSUE TITLE
[Question] How to extend framework to be able to make a REST API request

### ISSUE THREAD

**Issue by darran-kelinske-fivestars** [KasperskyLab/Kaspresso#169]
I would like to be able to make a REST API request to update an integrated system during a test. Is there a facility for this? If not, where would an appropriate hook / implementation be? Thank you!

**Comment by matzuk** [comment]
@darran-kelinske-fivestars Hi!
Maybe, [this tutorial](https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/04_How_to_write_autotests.md#test-data-for-the-test) will help you.
