### ISSUE TITLE
Provide few types of default `Kaspresso` implementations

### ISSUE THREAD

**Issue by dector** [KasperskyLab/Kaspresso#17]
Currently `Kaspresso.default()` is feature-loaded (e.g. contains a screenshot interceptor for each step).

As discussed, default implementation should be more lightweight and we can provide few more reconfigured implementations for different hypothetical environments (e.g. local, CI etc).

**Comment by dector** [comment]
I've checked all components in `Kaspresso.default()` implementation and seems that almost all of them are relatively "lightweight" except screenshot components: `ScreenshotStepWatcherInterceptor` and `TestRunnerScreenshotWatcherInterceptor`.

I suggest making `Kaspresso.default()` simple without screenshots and `Kaspresso.fullFeatured()` (requires better name) with full-featured testing environment..

**Comment by matzuk** [comment]
In master
