### ISSUE TITLE
[Q]: How to extract node property?

### ISSUE THREAD

**Issue by 4ntoine** [KasperskyLab/Kaspresso#170]
Hey, guys.

Please find my question on SO:
https://stackoverflow.com/questions/62921012/how-to-assert-element-property-value-with-espresso-web

I believe you're able to answer such a trivial question.
Thanks in advance!

**Comment by matzuk** [comment]
@eakurnikov you are a brilliant specialist in espresso-web area. Can you help?

**Comment by eakurnikov** [comment]
Hello. I have nothing to add to the answer on SO :)

**Comment by matzuk** [comment]
Looks outdated
