### ISSUE TITLE
Cannot run tests in kaspresso-sample project

### ISSUE THREAD

**Issue by cbxp** [KasperskyLab/Kaspresso#171]
Hi.
I am trying to 
1. clone https://github.com/KasperskyLab/Kaspresso/tree/master/kaspresso/kaspresso-sample
2. run `gradle connectedAndroidTest`

it starts running tests (on emulator), but freezes at some moment.

**Comment by ele638** [comment]
Hi!

Please check that you start ADB Server before start test (java -jar desktop.jar)

**Comment by asolntsev** [comment]
@ele638 thank you for the replay, I will try it.
But
1. Is it said in README or somewhere?
2. Wouldn't it be reasonable if Gradle script started this ADB server, so user wouldn't need to bother with it?

**Comment by matzuk** [comment]
@asolntsev there are some complaints that AdbServer usage is not so obvious.
We are going to improve this case in release 1.1.1.

**Comment by matzuk** [comment]
All tests have very obvious comments about using AdbServer.
In the opposite way, the test's error will contain a very clarified error text.
