### ISSUE TITLE
Where can I find screenshots?

### ISSUE THREAD

**Issue by cbxp** [KasperskyLab/Kaspresso#172]
Hi.

I wrote my tests using Kaspresso framework. Everything work find except I don't see any screenshots when my tests fail.

**Where can I find my screenshots?**

If I try to run `gradle connectedAndroidTest` in https://github.com/KasperskyLab/Kaspresso/tree/master/kaspresso/kaspresso-sample, I also don't see any screenshots. There is no `*.png` files in my project directory, neither in `/sdcard` folder.

**Comment by eakurnikov** [comment]
Hello. Screenshots must be in sdcard/screenshots folder. Check your permissions. And are there any errors in log when screenshots are taken?

**Comment by asolntsev** [comment]
As I mentioned, there is no screenshots in any of `sdcard` subfolders. What permissions do you mean? It's a usual Android emulator with all default permissions.

**Comment by eakurnikov** [comment]
1) Your tested app must have WRITE_EXTERNAL_STORAGE permission for making screenshots :) 
It is mentioned [here](https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/05_Device.md) and [here](https://github.com/KasperskyLab/Kaspresso/blob/master/kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/device/screenshots/Screenshots.kt)
Sorry if it was not so clear for user. Also, as you can see [here](https://github.com/KasperskyLab/Kaspresso/blob/master/kaspresso/kaspresso-sample/src/androidTest/java/com/kaspersky/kaspressample/device_tests/DeviceScreenshotSampleTest.kt), your test must have a grant permission rule for this. And then after test finishes you can find screenshots in sdcard.
2) It is the responsibility of test runner to run tests on devices and collect all data and resources from all devices after the tests are completed. Kaspresso is not responsible for this :) Also, you can create a simple gradle task to pull resources from devices after completing tests.

**Comment by asolntsev** [comment]
@eakurnikov Sorry for too many questions, I am just learning. :)

1. Well, I got screenshots in `/sdcard/screenshots` folder when I started `java -jar desktop.jar` before running tests. It was not trivial, though. :( 
2. But what if I want to test an application which doesn't have `WRITE_EXTERNAL_STORAGE` permission? 
3. Sorry, but why Appium can take screenshots without this permission?

**Comment by matzuk** [comment]
@asolntsev 
Hi!
There is a special [wiki page](https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/07_DocLoc.md) devoted to screenshots in the DocLoc (Documentation and Localization) process.
The issue of `sdcard`. @RuslanMingaliev do you have a similar problem with `sdcard`? And, do you want to save screenshots in internal memory, too?
`WRITE_EXTERNAL_STORAGE` @RuslanMingaliev, I suggest to research this topic.

**Comment by eakurnikov** [comment]
> @eakurnikov Sorry for too many questions, I am just learning. :)
> 
> 1. Well, I got screenshots in `/sdcard/screenshots` folder when I started `java -jar desktop.jar` before running tests. It was not trivial, though. :( 
> 2. But what if I want to test an application which doesn't have `WRITE_EXTERNAL_STORAGE` permission? 
> 3. Sorry for non-polite question, but why Appium can take screenshots without this permission?

1) desktop.jar is not needed for screenshots.
2) @RuslanMingaliev can help with some tricks, I think :)
3) I did not work with Appium. But it has the Node.js sever that creates a session for every test. So, I think screenshots can be pulled from devices via REST API. Kaspresso is much thiner and that's why it is more fast and stable.
