### ISSUE TITLE
Release 1.1.1: Breaking changes

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#175]
1. При использовании `device.logcat` желательно обязательно вызывать в before-секции метод `device.logcat.disableChatty`.

**Comment by RuslanMingaliev** [comment]
Нам нужно будет ещё пересобрать desktop.jar, так как мы поменяли названия пакетов. Мне видится, что в артефактах будут лежать несколько desktop.jar c именами, к примеру:
`desktop-1.0.0+.jar`
`desktop-1.1.0+.jar`
То есть версия минимальная Каспрессо будет в названии файла. А в идеале научиться бы поставлять desktop.jar до пользователя как можно быстрее без ручного запуска)

**Comment by matzuk** [comment]
Добавить в репозиторий AdbServer, что он deprecated
