### ISSUE TITLE
Очевидный AdbServer

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#176]
**Проблема**: люди не понимают, когда и как запускать AdbServer, для какой функциональности он критичен.
Что предлагается:
- [ ] Явно написать про AdbServer в Readme Kaspresso
- [ ] Пройтись по Wiki и явно написать, для какой функциональности нужен AdbServer, и как его подключить. Исходники смотрит небольшое кол-во разработчиков.
- [ ] Создать специальную gradle-таску, которая бы автоматически запускала desktop.jar на хосте у клиента и запускала бы все примеры. Информацию про эту таску поместить прямо в Readme.

**Comment by RuslanMingaliev** [comment]
> Явно написать про AdbServer в Readme Kaspresso

Вроде описано [здесь](https://github.com/KasperskyLab/Kaspresso#ability-to-call-adb-commands)?

> Пройтись по Wiki и явно написать, для какой функциональности нужен AdbServer, и как его подключить. Исходники смотрит небольшое кол-во разработчиков.

Можно попробовать, да. И про аннотацию написать специальную. 

>  Создать специальную gradle-таску, которая бы автоматически запускала desktop.jar на хосте у клиента и запускала бы все примеры. Информацию про эту таску поместить прямо в Readme.

Не думаю, что таска для сэмпла поможет чем-то. Шило на мыло, кмк

**Comment by asolntsev** [comment]
> Не думаю, что таска для сэмпла поможет чем-то. Шило на мыло, кмк

@RuslanMingaliev Как раз очень поможет. Я зачекаутил проект и запустил `gradle connectedAndroidTest` в папке `kaspresso-sample`. А тесты не работают. И ничего не понятно. 
* Хоть бы ошибка какая-нибудь летела, что "не найден ADB Server". 
* Или в README было бы написано, что нужно ещё запустить ADB Server. 
* А в идеале, чтобы пользователь вообще не должен был париться, и градл сам бы запустил этот ADB Server. А в конце прибил.

**Comment by RuslanMingaliev** [comment]
> @RuslanMingaliev Как раз очень поможет. Я зачекаутил проект и запустил gradle connectedAndroidTest в папке kaspresso-sample. А тесты не работают. И ничего не понятно.

Таска гредла в сэмпле не решает эту проблему. Мы можем её сделать, привязать к `connectedAndroidTest`, чтобы на старте поднимался `desktop.jar` и убивался после, но это будет работать только для сэмпла, и только для `connectedAndroidTest`. При этом тесты можно запускать не только так, но и с помощью любого из множества раннеров или через `adb shell am instrument`, например. Более того, ни разу не видел, чтобы на CI они запускались с `connectedAndroidTest`. 

Kaspresso – это про фреймворк для UI тестов, который решает все проблемы запуска тестов на девайсе, но не вне его. А все задачи связанные с хостом (включение/отключение desktop.jar, пулл скриншотов или логов с sd-карты, построение отчетов)  – это область ответственности раннера или скриптов, которые запускают тесты на эмуляторе. 

В будущем мы планируем бесшовную интеграцию с [Avito Test Runner](https://github.com/avito-tech/avito-android)-ом. И возможно даже с [marathon](https://github.com/Malinskiy/marathon). Вероятно напишем какой-то плагин для запуска тестов из IDE, который будет включать/отключать desktop.jar. Это не очень тривиальные задачи, но у нас есть представление, как их решать. Планируем что-то подобное сделать к релизу 1.2.0. @asolntsev, любая помощь приветствуется, можем обсудить голосом, как мы это видим, и вместе сделать крутые фичи быстрее)

**Comment by asolntsev** [comment]
@RuslanMingaliev 
1. А какой тогда командой запускаются тесты на CI, если не `gradle connectedAndroidTest`? Я в мобильниках новичок, пока только её и запускаю. 
2. Если это не область ответственности Kaspresso - ок, но тогда хотя бы в README надо написать, что нужен запуск desktop.jar. А то это прямо вот вообще неочевидно. 
3. Ну, и было бы хорошо иметь возможность скачивать desktop.jar мавеном или градлом.

**Comment by matzuk** [comment]
- Выводить понятную ошибку с подробным описанием.
В тестовых примерах явно на это указывать.
- В доке добавить раздел, как запустить сэмпл с описанием про desktop.jar.
