### ISSUE TITLE
Оптимизация работы AdbServer

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#177]
В коде присутствуют Thread.sleep, что может сказываться на перфомансе.
Нужно подумать, как соптимизировать код.

**Comment by RuslanMingaliev** [comment]
А есть примеры кода с Thread.sleep, которые потенциально вызывают проблемы с перфомансом?

**Comment by matzuk** [comment]
Жалоб нет. Предлагаю закрывать.
