### ISSUE TITLE
How to getText() from UiTextView

### ISSUE THREAD

**Issue by jakubparysz** [KasperskyLab/Kaspresso#178]
Hi,

I know it is not stackoverflow but I could not find any help, articles on the internet.

Is there any option to get text from UiTextView? 

Any discord to ask some technical stuff? 

Cheers

**Comment by matzuk** [comment]
Hi!
Sorry, we didn't do this method because Kautomator should be as similar to Kakao as possible. 
Do you need this method now? Maybe UiTextView assertions would be enough for you? If it doesn't then please describe your case to understand you better.

**Comment by sinthujan24** [comment]
@matzuk I have a usecase:

I need to retrieve the text of a video tile before tapping on it to ensure that the video opened has the text as one that is tapped

get text of video tile
tap video 
get text from video player
ensure the texts are the same

**Comment by Nikitae57** [comment]
Hi, @sinthujan24! Thank you for your submission. 

You could get text from UiTextView like so 
```kotlin
textView {
    view.interaction.uiObject2?.text
}
```

Please, tell us if you need further assistance with this issue
