### ISSUE TITLE
Junit 5 support

### ISSUE THREAD

**Issue by diklimchuk** [KasperskyLab/Kaspresso#179]
Hi!
Are there any plans to support JUnit5?
Currently it can be enabled for plan espresso tests with https://github.com/mannodermaus/android-junit5 on API above 26.

**Comment by matzuk** [comment]
Hi @diklimchuk!
Sorry for so long response time.
No, we have not had such plans. Is it actual now? And, do you have mind how to implement JUnit5 in Kaspresso?

**Comment by diklimchuk** [comment]
Hello!
We're continuing with running Junit4 tests, but it would be great to have such feature in future. We've migrated our unit tests to JUnit 5 and it's better to have the same framework to the entire codebase. I guess it will be a more common scenario for all kaspresso users going forward.

Regarting implementing JUnit 5 support, i don't remember exactly what the problem was. I'll try to take a look at this again later.

**Comment by matzuk** [comment]
Looks outdated
