### ISSUE TITLE
Generate and publish JavaDoc 

### ISSUE THREAD

**Issue by RuslanMingaliev** [KasperskyLab/Kaspresso#200]
Kaspresso documentation is currently stored at /docs directory in the repo. It's awkward, we should generate JavaDoc and host it at, for example, https://pages.github.com/

**Comment by AzamatCherchesov** [comment]
great idea

I close this issue as a duplicate to this one https://github.com/KasperskyLab/Kaspresso/issues/491

In this issue we will collect all the wishes for documentation
