### ISSUE TITLE
Any way to enable/disable Do Not Disturb setting?

### ISSUE THREAD

**Issue by rpattabi** [KasperskyLab/Kaspresso#203]
When I try to run my kaspresso tests on the cloud (e.g. firebase test lab or amazon device farm), they have some of the devices with Do Not Disturb (DnD) on. This makes the tests to fail. It would be great if I can automatically switch off DnD as part of the test.

I think I saw that you guys made toggling wifi button from notification panel possible recently. Could we do something similar for DnD?

**Comment by matzuk** [comment]
Hi!
Yep, it's possible. But we have to add that we try to do such things through ADB at first, and only in case of unsuccess, we continue the attempt via the notification panel.
Anyway, maybe you want to help us and implement the feature?

**Comment by rpattabi** [comment]
I will give it a try. I would appreciate any pointers to start with.

Regarding the ADB, it requires to run the server right? This may make it difficult (if not impossible) to run kaspresso tests on devices on the cloud (e.g. firebase test lab, amazon device farm, etc.). Not sure if it is the relevant place to discuss this. Any thoughts on this?

**Comment by matzuk** [comment]
You can start by observing the code of ```NetworkImpl```. The principles are so similar. 
Further, create a folder "Sounds" in [device folder](https://github.com/KasperskyLab/Kaspresso/tree/master/kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device). There will be two files in "Sounds": ```Sound``` and ```SoundImpl```. ```Sound``` must be included in [```Device``` class](https://github.com/KasperskyLab/Kaspresso/blob/master/kaspresso/src/main/kotlin/com/kaspersky/kaspresso/device/Device.kt).
```Sound``` will contain a method ```dontDisturbe(turnOn: Boolean)```.
```SoundImpl``` may contain attempts to make the action by clicking on NotificationPanel, clicking on Settings (you can open Sounds Settings via ```context.startActivity```) or using ADB server.
The important thing - you must check it on all devices (5.1, 6.0, 7.1, 8.0, 9.0, 10.0).

P.S. It's a suitable place to discuss =)
