### ISSUE TITLE
Help Needed to identify the element uniquely in TextView by using multiple conditions

### ISSUE THREAD

**Issue by mskumar1809** [KasperskyLab/Kaspresso#214]
Hi There,

I have a TextView and I am trying to identify the element using the property R.id.<id>, but due to the same id being used multiple times in the same view I am seeing the `androidx.test.espresso.AmbiguousViewMatcherException:`
matches multiple views in the hierarchy.

How can I add multiple conditions to the Screen elements by adding multiple conditions?

**Comment by mskumar1809** [comment]
Able to figure out how to add multiple conditions

**Comment by ShaxGOD** [comment]
test
