### ISSUE TITLE
How to check the unavailability of an element ?  

### ISSUE THREAD

**Issue by vajiras** [KasperskyLab/Kaspresso#217]
I want to verify that a banner is disappearing after I log in to the App

Business flow: 

1. Click on the banner on a screen
2. Then log in to the APP
3. Come back to the previous page (you will be logged in) 
4. Then I wanted to verify that the banner has been disappeared from the screen 
(Native APP)

I tried with these methods (isNotDisplayed(), isNotClickable(), but I got the following error:
"androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching"

Code:
ScreenName {
                    bannerTitleForTry {
                        isNotDisplayed()
                        isNotClickable()
                    }
               }
Note: The banner has defined in the Screen page object as ;
 val bannerTitleForTry = KButton{withId(R.id.banner_title)}

I can verify the available components/elements on that page but couldn't check the unavailable elements. 
**Do you have a specific method for it?**

**Comment by mskumar1809** [comment]
flakySafety(timeOut: 30000L) {
ScreenName {
bannerTitleForTry {
isNotDisplayed()
isNotClickable()
}
}
}

Try this

**Comment by vajiras** [comment]
Still, I'm getting the same error. 

step("Verify that the banner has disappeared from the page")
            {
                flakySafely (timeoutMs = 3000){
                    BookTipsScreen{
                        bannerTitleForTry{
                            isNotDisplayed()
                        }
                    }
                }
...

**Comment by mskumar1809** [comment]
continuously(FAKE_MAX_DELAY_MS) {
BookTipsScreen{
bannerTitleForTry{
isNotDisplayed()
} } } Try this

**Comment by vajiras** [comment]
same error. 
I feel like there should be a totally different way to check the unavailable components (**if the framework support to do so...**). 
Because it complains "NoMatchingViewException"

**Comment by matzuk** [comment]
Hi @vajiras!
Are you sure in this code `val bannerTitleForTry = KButton{withId(R.id.banner_title)}`?
Maybe, the element has a different id? Another option is to try to find the element by text, for example.

**Comment by vajiras** [comment]
Hi @matzuk ,
yes. the element is available. I'm checking the availability of it in a different step before I logged in to the App. 
thank you for replying.

**Comment by matzuk** [comment]
@vajiras Hi!
Is the issue actual?

**Comment by nazartal007** [comment]
Закрыто, но как будто актуально. Я вот тоже хотел бы проверить закрытие алерта. Но стандратными способами получаю NoMatchingViewException
