### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#219]
Fix [here](https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/02_Wrapper_over_UiAutomator.md).
![image](https://user-images.githubusercontent.com/2050571/100334081-5e88ba80-2fe4-11eb-89db-b076a837c5d5.png)

**Comment by sanmiAde** [comment]
@matzuk  Hi, if you don't mind, can you please explain what the issue is. Or has this been fixed already?

**Comment by matzuk** [comment]
@sanmiAde Hi! You just need to put missed `)` in the yellow area =)
