### ISSUE TITLE
JCenter Sunsetting; Artifact will be unavailable on February 1st 2022

### ISSUE THREAD

**Issue by dat-migdol** [KasperskyLab/Kaspresso#228]
Given the [sunsetting of JCenter next year](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), is there a plan to move this library to another artifact repository?

**Comment by RuslanMingaliev** [comment]
Yes, we'll switch to MavenCentral

**Comment by gildor** [comment]
Any updates on it?

**Comment by matzuk** [comment]
Work in progress still

**Comment by arorabharat1988** [comment]
Any update on this?

**Comment by matzuk** [comment]
@RuslanMingaliev ?

**Comment by AnoDest** [comment]
jcenter is down for at least a day. Unable to download the library. So it is a blocker

**Comment by mannodermaus** [comment]
Seems like Kaspresso 1.2.1 is available on Maven Central now. I was able to remove it from the list of JCenter exemptions in my build file and it still compiled. Thanks, everybody! ✨

**Comment by matzuk** [comment]
[Kaspresso 1.2.1](https://github.com/KasperskyLab/Kaspresso/releases/tag/1.2.1) in maven is ready!
