### ISSUE TITLE
[Question] Is there an example where I can do a Rest API call after test execution to update my Test status in Test rail

### ISSUE THREAD

**Issue by mskumar1809** [KasperskyLab/Kaspresso#231]

**Comment by mskumar1809** [comment]
I am looking to make a call to my test management tool based on the status of the test, is that possible in after block?

**Comment by matzuk** [comment]
Yep, you can. But remember, that your Rest API request must be called in blocking mode to wait for the response before completing the test.
Samples don't contain such a case, but the implementation looks pretty simple. If you will have obstacles then write me.

**Comment by matzuk** [comment]
Discussed in a personal chat
