### ISSUE TITLE
Screenshot testing

### ISSUE THREAD

**Issue by kotya341** [KasperskyLab/Kaspresso#233]
Hey folks,
just a quick question: 
is it possible to use your library as a replacement for a facebook screenshot [library](https://github.com/facebook/screenshot-tests-for-android)?
We already have the whole setup based on your `TestCase` and step approach, and it would be really handy to use the same  tooling for snapshot testing

**Comment by kotya341** [comment]
[Here](https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/07_DocLoc.md) you describe how to make a screenshot,
however it's not really clear what to do with them afterwards

**Comment by matzuk** [comment]
Hey!
About replacement of FB library. It depends on what function you need.
About our screenshotting. So, after tests, you just need to grab your screenshots from the device using simple ADB command. Have I understood your question right?

**Comment by matzuk** [comment]
Looks resolved
