### ISSUE TITLE
Allure steps information

### ISSUE THREAD

**Issue by stMayhem** [KasperskyLab/Kaspresso#236]
Hello. Should the reports generated by the allure include detailed steps? If I use the `step` method from the **allure** package, everything is ok, if I use **kaspresso** `step`, then in the report I get an empty list steps in generated json file. 
I use the [marathon](https://github.com/Malinskiy/marathon) as test orchestrator, but it seems it doesn't matter here

**Comment by matzuk** [comment]
Hi!
We are developing a feature that introduces several interceptors generating all allure info. Coming soon.

**Comment by stMayhem** [comment]
Thank you, we will wait. So the answer to my question is no? Now there is no way to add detailed steps to the allure report?

**Comment by matzuk** [comment]
Mentioned interceptors have to add all detailed information to the allure report =)
