### ISSUE TITLE
Flakysafely uasge is triggering java.lang.RuntimeException:

### ISSUE THREAD

**Issue by mskumar1809** [KasperskyLab/Kaspresso#266]
Seeing java.lang.RuntimeException: when using flakysafely and the intended behaviour is not as expected.

below is my test

```    fun mallNavigationTest() {
        before {
            activityTestRule.launchActivity(null)
        }.after {
        }.run {
            step("Login into the application") {
                compose(20000L) {
                    or(launchScreen.skipButton) {
                        isEnabled()
                    } then {
                        step("Skip flow") {
                            launchScreen {
                                skipButton {
                                    click()
                                }
                            }
                        }
                    }
                    or(launchScreen.userName) {
                        isEnabled()
                    } then {
                        step("Login flow") {
                            launchScreen {
                                userName {
                                    click()
                                }
                            }
                        }
                    }
                }
                launchScreen {
                        userName {
                            typeText("peshy16711")
                        }
                        password {
                            typeText("XXjddirdj")
                        }
                        login {
                            click()
                        }
                        discover {
                            flakySafely(20_000) {
                            isVisible()
                            click()
                        }
                    }
                }
            }
            step("Navigate to Mall") {
                launchScreen {
                    mallBanner {
                        click()
                    }
                    closeBanner {
                        click()
                    }
                    mallScreen {
                        isDisplayed()
                        isEnabled()
                    }
                }
            }

        }
    }```

The test runs fine if there is no `flakysafely` block, else it throws the below exception
```java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not request layout for 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Root:```

Other observations:
1. if Flakysafely is used at the screen level, then the EditText fields actions are running in loop.
2. If the flakysafely is added to any other element the exception is encountered as stated above.

My config is
androidTestImplementation "com.kaspersky.android-components:kaspresso:1.2.1"

Kindly please help to have a look the issue.

**Comment by matzuk** [comment]
Hi @mskumar1809!
The root cause of the mentioned problem can be anything. It's very hard to predict what goes wrong. Can you create a sample reproducing this behavior?
Maybe @Vacxe has some ideas?

**Comment by mskumar1809** [comment]
Hi @matzuk,

I have an update on the issue I have below screen file

`object LaunchScreen : KScreen<LaunchScreen>() {

    override val layoutId: Int? = R.layout.activity_main // initially I didnt have the values for this layoutID which returned the root error
//        get() = TODO("Not yet implemented") 
    override val viewClass: Class<*>? = SplashScreenActivity::class.java  // initially I didnt have the values for this viewClass which returned the root error
//        get() = TODO("Not yet implemented")

    val skipButton = KButton {withText("SKIP")}
    val userName = KEditText{withId(R.id.emailACTV)}
    val password = KEditText{withId(R.id.passwordET)}
    val login = KTextView {withId(R.id.loginBTN)}
    val discover = KNavigationView{withId(R.id.navigation_discover)
        withContentDescription("Discover")
    }
    val mallBanner = KTextView{withText("Go to LYKA Mall")}
    val closeBanner = KImageView{withId(R.id.btn_close)}
    val mallScreen = KTextView{withText("LYKA Mall")}
}`

Below is my working test

`    fun mallNavigationTest() {
        before {
            activityTestRule.launchActivity(null)
        }.after {
        }.run {
            step("Login into the application") {
                compose(20000L) {
                    or(launchScreen.skipButton) {
                        isEnabled()
                    } then {
                        step("Skip flow") {
                            launchScreen {
                                skipButton {
                                    click()
                                }
                            }
                        }
                    }
                    or(launchScreen.userName) {
                        isEnabled()
                    } then {
                        step("Login flow") {
                            launchScreen {
                                userName {
                                    click()
                                }
                            }
                        }
                    }
                    or(launchScreen.discover){
                        isVisible()
                    } then {
                        step("Already logged in"){

                        }
                    }
                }
                launchScreen {
                        userName {
                            typeText("reshu1611")
                        }
                        password {
                            typeText("@MyLyka1611@")
                        }
                        login {
                            click()
                        }
                        discover {
                            flakySafely(20_000) {
                            isVisible()
                            click()
                        }
                    }
                }
            }
            step("Navigate to Mall") {
                    launchScreen {
                        mallBanner {
                            flakySafely {
                                click()
                            }
                        }
                        closeBanner {
                            click()
                        }
                        mallScreen {
                            isDisplayed()
                            isEnabled()
                        }
                    }
                }
            }

    }`

I have few observations when I use the flakysafely at different areas in my test

Try 1 : Changed the flakysafely to the screen level as below
`.run {
            step("Login into the application") {
                compose(20000L) {
                    or(launchScreen.skipButton) {
                        isEnabled()
                    } then {
                        step("Skip flow") {
                            launchScreen {
                                skipButton {
                                    click()
                                }
                            }
                        }
                    }
                    or(launchScreen.userName) {
                        isEnabled()
                    } then {
                        step("Login flow") {
                            launchScreen {
                                userName {
                                    click()
                                }
                            }
                        }
                    }
                    or(launchScreen.discover){
                        isVisible()
                    } then {
                        step("Already logged in"){

                        }
                    }
                }
                
                launchScreen {
                    flakySafely(20_000) {
                        userName {
                            typeText("reshu1611")
                        }
                        password {
                            typeText("@MyLyka1611@")
                        }
                        login {
                            click()
                        }
                        discover {
                            isVisible()
                            click()
                        }
                    }
                }
            }
            step("Navigate to Mall") {
                    launchScreen {
                        mallBanner {
                            flakySafely {
                                click()
                            }
                        }
                        closeBanner {
                            click()
                        }
                        mallScreen {
                            isDisplayed()
                            isEnabled()
                        }
                    }
                }
            }`

Observation 1:
- After clicking on `login` button, while the screen is loading the test is not moving forward but is looking for `username` and failing.

Is this the expected behaviour? coz with 1.1 version of Kaspresso, I was able to use Flakysafely at screen level without any issue, now I see this behaviour.

If this is the expected then how can we specify flakysafely at screen level and not look for already found elements?

Any suggestions would be really appreaciated.

**Comment by matzuk** [comment]
@mskumar1809 Hi!
If your screen appears not immediately then try to use `by lazy` in a declaration of elements in `KScreen` (`LaunchScreen`, I think in your case).
The example: `val skipButton by lazy { KButton { withText("SKIP") } }`

**Comment by RuslanMingaliev** [comment]
Hi, @mskumar1809 !
Could you please provide a working sample with an incorrect behavior? Or this issue is not actual for you anymore?

**Comment by AzamatCherchesov** [comment]
Closed due to the lack of activity
