### ISSUE TITLE
Provide alternative TypeText method

### ISSUE THREAD

**Issue by dsvoronin** [KasperskyLab/Kaspresso#27]
as used in avito: https://github.com/avito-tech/android-ui-testing/blob/master/ui-testing-core/src/main/java/com/avito/android/test/element/field/actions/TypeText.kt

looks like better solution in every scenario.
Problem is InputConnection API is being closed as internal

cc @dimorinny as an author of this method

**Comment by dsvoronin** [comment]
https://stackoverflow.com/questions/55970137/bypass-androids-hidden-api-restrictions/55970138#55970138 (https://www.reddit.com/r/androiddev/comments/deyz14/apparently_you_can_destroy_hidden_api_blacklist/)
could help for a while

**Comment by matzuk** [comment]
@dsvoronin news? =)

**Comment by dsvoronin** [comment]
No news unfortunately, i am not following test framework development lately and don't know if i'll have time to support this feature in future in kaspresso
