### ISSUE TITLE
Build issue with targetSdk  = 31

### ISSUE THREAD

**Issue by Manuiq** [KasperskyLab/Kaspresso#329]
When targeting Android 12 (targetSdk = 31) in android project I receive this error during gradle sync:

`Error: android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.`

Downgrading to targetSdk = 30 solves the issue but forces the app not to support latest Android 12 features.
Probably there are some internal activities (maybe from other libraries) that have not set up this `android:exported` flag

**Comment by RuslanMingaliev** [comment]
Hi there, 
How is it related to Kaspresso? The error message contains a link with an explanation of the issue.

**Comment by Manuiq** [comment]
Hi, my assumption is Kaspresso depends on some external library that has an activity declared (because Kaspresso Manifest file contains no activities) without this `android:exported` flag. For now only removal of kaspresso dependency or downgrading to targetSdk 30 works

**Comment by RuslanMingaliev** [comment]
I've found the problem. Kaspresso depends on AndroidX Test Core 1.3 which [provides](https://github.com/android/android-test/blob/androidx-test-1.3.0/core/java/androidx/test/core/AndroidManifest.xml
) its own activities. Update Kaspresso to the newest 1.4.0 version or bump the version of AndroidX Test Core up manually to 1.4.0. It [contains](https://github.com/android/android-test/blob/androidx-test-1.4.0/core/java/androidx/test/core/AndroidManifest.xml) the `android:exported` flag.

**Comment by Manuiq** [comment]
Cool! Thanks for figuring out the problem, will try it out
