### ISSUE TITLE
Add callback to flakySafely for tracking actual timeout

### ISSUE THREAD

**Issue by phansier** [KasperskyLab/Kaspresso#34]
There is an idea to add callback to flakySafely function of actual timeout needed to pass the action.
Now timeouts in tests are set according to internal feeling of developer.
After such callback will be add there will be an opportunity to have a statistics on it and to configure actual timeout according to this statistics.
Therefore in case of fail tests will not wait for extra timeout and will fail earlier.

**Comment by priomino** [comment]
Maybe there is such feature in database saved from marathon?

**Comment by matzuk** [comment]
Close this issue because there were not any requests to implement a similar thing
