### ISSUE TITLE
allure support dependency issue 

### ISSUE THREAD

**Issue by 1YaHo01** [KasperskyLab/Kaspresso#341]
Hello! 
i try to add allure-support into my project , but it's no works 
according to https://github.com/KasperskyLab/Kaspresso/blob/master/wiki/09_Kaspresso-Allure.md
i've add to my build.gradle dependencies 
```
dependencies {

...

androidTestImplementation "com.kaspersky.android-components:kaspresso-allure-support:1.4.0"

androidTestImplementation "com.kaspersky.android-components:kaspresso:1.4.0"
}
```

gradle project is synced

but when i try to create class and start coding it shows unresolved reference error (test class under the androidTest folder)
![image](https://user-images.githubusercontent.com/45675057/144598913-aa9ccf74-e8e8-4863-a4d6-d7d65aa17deb.png)

i've tried clean project , rebuilt  and etc. but it still no working ( 

Can you please help me ?

**Comment by matzuk** [comment]
@RuslanMingaliev need your help

**Comment by sergio-sastre** [comment]
@1YaHo01 
While fixing this issue, you can use Kaspresso and Allure 1.3.0 dependencies
It is not missing there.

**Comment by matzuk** [comment]
Hi everyone!
We are working on this problem. Currently, there is a small hack to work around the issue. Just copy-paste [ComposeSupportKaspressoBuilder.kt](https://github.com/KasperskyLab/Kaspresso/blob/master/compose-support/src/main/java/com/kaspersky/components/composesupport/config/ComposeSupportKaspressoBuilder.kt) and [AllureSupportKaspressoBuilder.kt](https://github.com/KasperskyLab/Kaspresso/blob/master/allure-support/src/main/kotlin/com/kaspersky/components/alluresupport/AllureSupportKaspressoBuilder.kt) classes into your project keeping package naming. It'll give you the same functionality and allow you to use compose or allure support.
