### ISSUE TITLE
Тесты не запускаются с версии 1.4.0

### ISSUE THREAD

**Issue by hotmule** [KasperskyLab/Kaspresso#347]
Точнее, тесты собиратся и запускаются, но дальше ничего не происходит, в результатах отображается, что пройдено 0 тестов из 0, похоже, это как-то связано с [Espresso 3.4.0](https://stackoverflow.com/questions/70622183/espresso-tests-not-running-in-android-studio), помогает откат до 1.3.0

<img width="1877" alt="Screenshot 2022-01-12 at 22 39 10" src="https://user-images.githubusercontent.com/37577810/149209931-6958e522-6d0a-44da-b490-2a445f3eac23.png">

**Comment by matzuk** [comment]
попробуй отключить orchestrator в build.gradle

**Comment by hotmule** [comment]
а он и не включен, вроде как 🤔

**Comment by hotmule** [comment]
Помогло исключение `protobuf-lite` из зависимости
`androidTestImplementation(Libraries.Tests.Kaspresso.core) { exclude(module = "protobuf-lite") }`

**Comment by ln-12** [comment]
Just in case someone has the same issue with protobuf, for me the error was:
```
java.lang.IllegalAccessError: Method 'com.google.protobuf.LazyStringArrayList com.google.protobuf.LazyStringArrayList.emptyList()' is inaccessible to class 'com.example.app.MyClass' (declaration of ''com.example.app.MyClass' appears in /data/app/~~L30fdXd1XWLvWbs7E5CFGQ==/'com.example.app-jd3bzdZbBF74IdQvF48gUg==/base.apk!classes14.dex)

```

I solved it by excluding the group instead:
```
    androidTestImplementation("com.kaspersky.android-components:kaspresso:1.5.3") {
        exclude group: "com.google.protobuf"
    }
    androidTestImplementation("com.kaspersky.android-components:kaspresso-allure-support:1.5.3") {
        exclude group: "com.google.protobuf"
    }
    androidTestImplementation("com.kaspersky.android-components:kaspresso-compose-support:1.5.3") {
        exclude group: "com.google.protobuf"
    }
    androidTestImplementation("org.hamcrest:hamcrest:2.2") {
        exclude group: "com.google.protobuf"
    }
```
