### ISSUE TITLE
Google Maps testing

### ISSUE THREAD

**Issue by hotmule** [KasperskyLab/Kaspresso#348]
Is it possible using KAutomator to interact with a marker on the Google Map, as is done in [examples](https://stackoverflow.com/a/30519001/9277500) with a regular UiAutomator?

**Comment by matzuk** [comment]
@Vacxe, I remember that you did something similar.

**Comment by hotmule** [comment]
I implemented it like this:

>val map: UiView = UiView { withContentDescription("SampleDeliveryMapContentDescription") }
>val marker: UiView = UiView { withContentDescription(Pattern.compile(".*MarkerTitle.*")) }

**Comment by Nikitae57** [comment]
Hi, @hotmule! Thank you for your submission. We described google maps interaction in docs for future references. Thank you!
Closing this issue
