### ISSUE TITLE
Missing extension functions

### ISSUE THREAD

**Issue by aasitnikov** [KasperskyLab/Kaspresso#351]
If you remove [META-INF/kotlin_module](https://github.com/KasperskyLab/Kaspresso/blob/master/build-logic/android/src/main/kotlin/convention.android-base.gradle.kts#L19-L21), then Kotlin compiler won't be able to resolve extension functions. More info: [KT-9770](https://youtrack.jetbrains.com/issue/KT-9770), [old Kotlin Blog post](https://blog.jetbrains.com/kotlin/2015/06/improving-java-interop-top-level-functions-and-properties/)

**Comment by RuslanMingaliev** [comment]
It's a good point, thank you for the issue. I'll take a close look soon
