### ISSUE TITLE
[ReadMe] Дополнить информацией про фильтрацию тестов

### ISSUE THREAD

**Issue by KRUG500** [KasperskyLab/Kaspresso#361]
1. Добавить описание как работать с аннотациями (com.kaspersky.kaspresso.annotations)
2. Добавить примеры как это выглядит в тестах
3. Показать запуск тестов через adb с выбранными аннотациями

**Comment by eakurnikov** [comment]
Привет. Фильтрация тестов по аннотациям это стандартная фича JUnit, ну и составлением тест плана, собственно, занимается раннер. Можно добавить в туториал по запуску, но не в README.

**Comment by matzuk** [comment]
Добавил в описание того, что мы хотим в туториале. Issue тогда закрываю.
