### ISSUE TITLE
java.lang.NoSuchFieldError: No static field INSTANCE of type Lio/qameta/allure/android/AllureAndroidLifecycle; Allure 2.4.0

### ISSUE THREAD

**Issue by kuFEAR** [KasperskyLab/Kaspresso#375]
Hi, 
does 1.4.1 contain update fix for allure dependencies 2.4.0?  https://github.com/KasperskyLab/Kaspresso/pull/356

They changed the implementation from `object AllureAndroidLifecycle` to `class AllureAndroidLifecycle` and as result it cause the trace:
```
java.lang.NoSuchFieldError: No static field INSTANCE of type Lio/qameta/allure/android/AllureAndroidLifecycle; in class Lio/qameta/allure/android/AllureAndroidLifecycle; or its superclasses (declaration of 'io.qameta.allure.android.AllureAndroidLifecycle' appears in )
	at com.kaspersky.components.alluresupport.interceptors.step.AllureMapperStepInterceptor.<init>(AllureMapperStepInterceptor.kt:13)
	at com.kaspersky.components.alluresupport.AllureSupportKaspressoBuilderKt.addAllureSupport(AllureSupportKaspressoBuilder.kt:32)


```
and when I decompiled AllureMapperStepInterceptor I see old implementation on `object` INSTANCE, and if downgrade to 1.4.0 it looks same
<img width="663" alt="Screenshot 2022-08-01 at 09 50 05" src="https://user-images.githubusercontent.com/4124981/182089159-25126108-4686-4850-afdb-81db64d5a59e.png">

**Comment by kuFEAR** [comment]
I see it's already fixed https://github.com/KasperskyLab/Kaspresso/commit/e48d9c0db11e5aebf7f1f6bd589a1695efe271bc )
okay, I will investigate the error

**Comment by Nikitae57** [comment]
Hi, @kuFEAR! Thank you for your submission. Please, check out Kaspresso 1.4.2 and close this issue if your problem solved

**Comment by Nikitae57** [comment]
Please, feel free to re-open if you still experience this issue. Please, notice, that there's a [PR](https://github.com/KasperskyLab/Kaspresso/pull/401) related to your issue
