### ISSUE TITLE
typetext to SearchView not works (text ingnored)

### ISSUE THREAD

**Issue by priomino** [KasperskyLab/Kaspresso#39]
Если попытаться сделать typetext в такой элемент, то ничего не впечатается

<item
        android:id="@+id/menu_search"
        android:title="@string/app_l******rch"
        app:actionViewClass="androidx.appcompat.widget.SearchView"
        android:imeOptions="actionSearch"
        app:showAsAction="always"/>

**Comment by priomino** [comment]
Пример элемента:

    <item
        android:id="@+id/menu_search"
        android:title="@string/app_l***arch"
        app:actionViewClass="androidx.appcompat.widget.SearchView"
        android:imeOptions="actionSearch"
        app:showAsAction="always"/>

**Comment by RuslanMingaliev** [comment]
@priomino 
символы кириллица или латиница?

**Comment by priomino** [comment]
цифры
например: +7999555545 или 8 (823) 347-55-44

**Comment by matzuk** [comment]
is it actual?

**Comment by priomino** [comment]
Not any more
