### ISSUE TITLE
Empty object "steps" in allure result json

### ISSUE THREAD

**Issue by ursar** [KasperskyLab/Kaspresso#400]
**To Reproduce**
1. Run test "counter" (com.kaspersky.kaspresso.alluresupport.sample.AllureSupportCustomizeTest#counter);
2. Open Allure result json file.

**Actual behavior**:
Object "steps" empty.
[1.4.2.json.zip](https://github.com/KasperskyLab/Kaspresso/files/9866874/1.4.2.json.zip)

**Expected behavior**:
Object "steps" contains information about step from test.
[1.4.1.json.zip](https://github.com/KasperskyLab/Kaspresso/files/9866867/1.4.1.json.zip)

**Environment:**
 - Kaspresso 1.4.2
 - AVD API Level 29

**Comment by Nikitae57** [comment]
Thank you for reporting this issue! Corresponding pull request was merged. Fix will be present in the next release
