### ISSUE TITLE
No video artifacts in Kaspresso Allure

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#407]
**Describe the bug**
There is no video artifact (or it's empty one) after Kaspresso Allure test completion.

**To Reproduce**
Run any Kaspresso Allure example

**Desktop (please complete the following information):**
 - OS: Mac OS (M1)
 - Version: 1.4.2

**Smartphone (please complete the following information):**
 - Device: Emulator (ARM)

**Comments
Worked on 1.4.1 basing on feedbacks

**Comment by Nikitae57** [comment]
Suppose the issue is that dir is created instead of file
![image](https://user-images.githubusercontent.com/21224897/199677050-1f29ae02-22b5-4659-86ef-f2cfa01423a4.png)

**Comment by Nikitae57** [comment]
And looks like it's a permission issue
`adb shell screenrecord  /sdcard/file.mp4` runs perfectly fine, but `adb shell run-as com.kaspersky.kaspresso.alluresupport.sample screenrecord /data/user/0/com.kaspersky.kaspresso.alluresupport.sample/files/video/com.kaspersky.kaspresso.alluresupport.sample.AllureSupportTest/counter/test.mp4` creates an mp4 header file and doesn't write actual screen record into it
