### ISSUE TITLE
Swipe actionas are not working on API 33

### ISSUE THREAD

**Issue by IgorResetic** [KasperskyLab/Kaspresso#420]
**Describe the bug**
The swipe actions on android devices with API 33 are not working, and instead of swipe, click action is performed. This is a known issue with espresso and is fixed with version 3.5.0-alpha07. 

When can we expect kaaspresso is updated to use the newer version of espresso?

**To Reproduce**
Run any test on RecyclerView on a device with API 33

**Expected behavior**
A swipe action is done instead of a click. 

**Smartphone (please complete the following information):**- 
 - Device: Pixel 6
 - OS: API 33
 - Version 1.4.2

**Comment by Nikitae57** [comment]
Hi, @IgorResetic! I've checked current master, it seems that recycler swipe actions are working. Kaspresso 1.5.1 uses espresso 3.5.0, so you could use it. Feel free to re-open this issue if something is wrong
