### ISSUE TITLE
Cannot setup interceptors :(

### ISSUE THREAD

**Issue by michalorminski** [KasperskyLab/Kaspresso#433]
Hi,

Apologies for the stupid question, but what and how should I use to implement a solution for a following type of problem:
"If a dialog X appears in a random moment in a Kaspresso test, close it by click on a UiButton with and id 'dismiss'". If the dialog is not appearing, just quickly move on with the test.

I've read the docs and figured out the maybe interceptors (or Watchers as we are also using some regular UiAutomator in the code but thats a different story) could help. 

I cannot figure out though how to setup an interceptor that looks over the tests and tries to click "dismiss" if an UiObjectNotFound will appear in some random moment and ofc if the "dismiss" button exist.

I am also not sure if I understand the idea of interceptors/watchers right probably not. :/

Thx in advance for the help.

**Comment by michalorminski** [comment]
any1? :(

**Comment by Areyana** [comment]
Thx for issue, we know about system dialog interceptor problem, i'll check it. As for interceptors they probably work without any code from your side in a "automatic" way (as for dialog/flaky/autoscroll interceptors for example).

**Comment by Areyana** [comment]
fixed in #460

**Comment by michalorminski** [comment]
Hi @Areyana , thx for fixing but that was not quite the issue I witnessed. I moved on a little bit though. Now I'm stuck at this example:

`lass SomeTest {
    @Before
    fun setup() {
        KautomatorConfigurator { // Kautomator runtime
            intercept {
                onUiInteraction { // Intercepting calls on UiInteraction classes across whole runtime
                    onPerform { uiInteraction, uiAction -> // Intercept perform() call
                        testLogger.i("KautomatorIntercept", "interaction=$uiInteraction, action=$uiAction")
                    }
                }
            }
        }
    }

    @Test
    fun test() {
        MyScreen {
            intercept {
                onUiInteraction { // Intercepting calls on UiInteraction classes while in the context of MyScreen
                    onCheck { uiInteraction, uiAssert -> // Intercept check() call
                        testLogger.i("KautomatorIntercept", "interaction=$uiInteraction, assert=$uiAssert")
                    }
                }
            }

            myView {
                intercept { // Intercepting ViewInteraction calls on this individual view
                    onPerform(true) { uiInteraction, uiAction -> // Intercept perform() call and overriding the chain
                        // When performing actions on this view, Kautomator level interceptor will not be called
                        // and we have to manually call UI Automator now.
                        Log.d("KAUTOMATOR_VIEW", "$uiInteraction is performing $uiAction")
                        uiInteraction.perform(uiAction)
                    }
                }
            }
        }
    }
}`

When I use the interceptor inside the @Test method - it works perfectly. But when i try to use it in the @Before method - it completely does not work (no logs - it seems it does not intercept anything).

**Comment by Areyana** [comment]
@michalorminski Can you check [this example](https://github.com/KasperskyLab/Kaspresso/blob/master/samples/kautomator-sample/src/androidTest/java/com/kaspersky/kaspresso/kautomatorsample/test/InterceptorTest.kt). Cause i think, @Before usage on interceptors has no any effect.
