### ISSUE TITLE
Support html for allure attachments or let choose type

### ISSUE THREAD

**Issue by DEADMC** [KasperskyLab/Kaspresso#434]
Currently we dont have options to add html reports because we cant use `Allure.attachment` directly and at [AttachToReport.kt](https://github.com/KasperskyLab/Kaspresso/blob/master/allure-support/src/main/kotlin/com/kaspersky/components/alluresupport/files/AttachToReport.kt) supported types are only:
- text/plain
- text/xml
- image/png
- video/mp4

Also usually its much easier to work with `InputStream` than with `File`. For example if I want to attach some string to my report I can easily get `InputStream` for it, but if I can work with file only I have to save and create it, in other words I do much more actions than I could do

Would be perfect to choose type and be able to use InputStream instead of file too

**Comment by Nikitae57** [comment]
Hi, @DEADMC!  We exposed allure dependency, so in the next release you would be able to work with any attachments you want
