### ISSUE TITLE
Не работает takeFullWindowAndApply и takeFullWindow

### ISSUE THREAD

**Issue by ABluvshteinAgimagroup** [KasperskyLab/Kaspresso#476]
**Describe the bug**
Обновился до 1.5.1 при использовании takeFullWindowAndApply доходит до строчки "if (originalHeight < view.measuredHeight) {" и там обычно по условию не проходит, как следствие попадает на строчку "TODO("External Full Window Screenshot not yet implemented")"
Если if проходит, то там скрин не превышает размер экрана, т.е. если контен больше экрана, то фуллскрин сделать не получается. Пробовал руками на дебаге менять параметры originalHeight и measuredHeight, так же на разных устройствах, но фуллСкрины не делаются и так.

**To Reproduce**
Вызвать takeFullWindowAndApply/takeFullWindow в любом месте, где необходим скроллинг/свайп для просмотра экрана. Может корректно сработать если на экран "без сролла", но редко

**Expected behavior**
Корретно делаются фулл срины и сохраняются

**Smartphone (please complete the following information):**
 - Device: Разные эмуляторы android, в основном 11.0 x86

**Comment by Areyana** [comment]
@ABluvshteinAgimagroup Привет, закинь пожалуйста пример теста и лаяута который использовался

**Comment by ABluvshteinAgimagroup** [comment]
Привет, узнавал, у нас соглашение о неразглашении, тимЛид говорит код нельзя высылать. А лаяута не важен, я пробовал на разных виртуалках, например стандартный Pixel 4 XL API 30
Даже если на каком-то лаяуте проходит этот if, то значит контент в пределах экрана, смысла в фулл скрине нет.

**Comment by Areyana** [comment]
@ABluvshteinAgimagroup проверил на наших санити тестах, все отрабатывает корректно. Нужен более детальный пример, чтобы выяснить откуда проблема. До примера закрываю.
