### ISSUE TITLE
Не всегда срабатывает клик по View в боттомшите

### ISSUE THREAD

**Issue by ipopov-belkacar** [KasperskyLab/Kaspresso#483]
Дано: expanded боттомшит с MaterialButton'ами внутри вертикального LinearLayout.
В тесте не всегда срабатывает клик по MaterialButton'у (любому).
Логи при этом говорят, что клик произошёл:

> ViewInteraction: Performing 'single click' action on view (view.getId() is <2131429247/ru.belkacar.belkacar.debug:id/supportServiceItemButton>)
> KASPRESSO: single click on MaterialButton(id=supportServiceItemButton;text=Support;) 

Однако в UI реакции на клик нет, и если повесить в приложении лог на обработчик клика, этот лог молчит - то есть клика действительно нет. Почему же каспрессо уверен, что он есть? Судя по вьюиерархии и ассертам, кнопка видна и кликабельна: 

> MaterialButton{id=2131429247, res-name=supportServiceItemButton, visibility=VISIBLE, width=1080, height=157, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@70955f3, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=973.0, text=Support, input-type=0, ime-target=false, has-links=false, is-checked=false}

Я думал, может обработчик не успевает повеситься, но логи говорят обратное (обработчик вешается до вызова клика). Тем не менее, если воткнуть Thread.sleep(1000) перед вызовом openSupportServiceDialog() - всё начинает работать. Или если в процессе теста ткнуть кнопку вручную. 
Следовательно, логично предположить, что клик каспрессо по кнопке порой происходит слишком быстро, и каспрессовское "автодожидание появления вью до взаимодействия с ней" не срабатывает, но почему? И почему нет эксепшна, а во вьюиерархии с кнопкой всё в порядке? И почему это плавающее поведение? И как это предотвратить, кроме рандомного Thread.sleep?

```
object NavigationFragmentScreen: KScreen<NavigationFragmentScreen>() {
    override val layoutId: Int = R.layout.fragment_navigation
    override val viewClass: Class<*> = NavigationFragment::class.java

    private val burgerMenuButton = KButton { withId(R.id.burgerMenuButton) }

    fun openMainMenu() {
        burgerMenuButton {
            click()
        }
    }
}

object MainMenuFragmentScreen : KScreen<MainMenuFragmentScreen>() {
    override val layoutId: Int = R.layout.fragment_main_menu
    override val viewClass: Class<*> = MainMenuFragment::class.java

    private val supportServiceItemButton = KButton { withId(R.id.supportServiceItemButton) }

    fun openSupportServiceDialog() {
        supportServiceItemButton {
            isVisible()
            click()
        }
    }
}

class OpenSupportScreenTest: TestCase() {

    @get:Rule
    val primaryActivityRule = activityScenarioRule<PrimaryActivity>()

    @Test
    fun testOpenSupportScreen() = run {

        NavigationFragmentScreen {
            openMainMenu()
        }

        MainMenuFragmentScreen {
            openSupportServiceDialog()
        }

        SupportFragmentScreen {
            checkElements()
        }
    }
}
```

Боттомшит выглядит, как на скриншоте.
![Снимок экрана 2023-01-19 в 01 05 01](https://user-images.githubusercontent.com/102363874/213305889-9d29966f-fb64-4234-80cc-76f3921bdce4.png)

Kaspresso 1.5.1
Эмулятор Pixel 5 API 30

P.S.: я пытался сделать новый проект, примерно повторить там нашу вёрстку и всё остальное, но повторить этот баг у меня не получилось.

**Comment by Nikitae57** [comment]
Hi, @ipopov-belkacar! Kaspresso logs click being performed successfully because the view indeed was found and clicked successfully, at least kaspresso backend (espresso or uiAutomator) reports so. The problem is that the view itself isn't ready to handle the click. I would suggest 2 things: 
1. disable animation
2. wait until main thread idles before performing problematic clicks
The first step could be done using kaspresso, the second one, unfortunately, isn't. Forcing main thread idling on each click is a significant breaking change which may brake a lot of written tests out there.

Please, try out my suggestions and re-open the issue if they won't help
