### ISSUE TITLE
Missing allure result json files in allure-results folder

### ISSUE THREAD

**Issue by ol-le** [KasperskyLab/Kaspresso#559]
**Describe the bug**
Allure results files (e.g. `*-result.json`, `*-container.json`) are missing in the `allure-results` folder, 

(attachments: videos, screenshots, logcat dumps are present in the allure-results folder)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tests with allure support enabled, using [wiki](https://kasperskylab.github.io/Kaspresso/Wiki/Kaspresso_Allure/)
2. Navigate to `/sdcard/Documents/allure-results/` on emulator and check the contents of the folder -> No allure results json files are present in the `allure-results` folder -> allure report cannot be generated

**Expected behavior**
All allure results files that are needed for report generation are located in the folder `/sdcard/Documents/allure-results/`

**Screenshots**
<img width="560" alt="Screenshot 2023-08-21 at 14 51 50" src="https://github.com/KasperskyLab/Kaspresso/assets/3470515/9a3c8022-3e93-43e7-99c1-8b3ebb2738ec">

also in the logs I get error messages from `AllureLifecycle`, that the steps cannot be started / updated as no test cases are running, e.g.

```
AllureLifecycle Could not start step: no test case running
AllureLifecycle Could not add attachment: no test is running
AllureLifecycle Could not update step: step with uuid e4cc8470-4af0-4e61-be6d-159be3e69146 
```

**Emulator (please complete the following information):**
- Pixel_2_API_30 - arm64-v8a - google-apis
- Android_TV_720p_API_31 - arm64-v8a - google-apis
Also reproducible on real devices

**Additional context**
I'm using `allure.properties` resource file to force `allure-results` location with to write to a public folder that doesn't require extra permissions with this property
`allure.results.directory=/sdcard/Documents/allure-results/`

The tests are executed with `testInstrumentationRunner "com.kaspersky.kaspresso.runner.KaspressoRunner"` 
Emulator: Android emulator version 33.1.17.0 (canary release)
Kaspresso version: 1.5.2
Gradle plugin version: 8.0.2
Environment: Mac Mini Apple M2 macOS Ventura 13.5

**Comment by Nikitae57** [comment]
Hi, @ol-le! Please, try out kaspresso 1.5.3 with `withForcedAllureSupport` builder and remove allure.results.directory and allure.results.useTestStorage=true from properties. Please, re-open if the issue still occures
