### ISSUE TITLE
Trying to implement Kaspresso

### ISSUE THREAD

**Issue by capnac** [KasperskyLab/Kaspresso#571]
Hi, I have been trying to integrate Kaspresso by following the steps explained in your documentation and one point is quite confusing. `it is necessary to inherit from the KScreen class`=> there is no info what KSscreen is as I am getting `unresolved reference: screens ` as soon as I am importing it `import com.kaspersky.kaspresso.screens.KScreen` And Implement Members are not found for `object MainScreen : KScreen<MainScreen>()` 
<img width="446" alt="Screenshot 2023-09-10 at 16 13 43" src="https://github.com/KasperskyLab/Kaspresso/assets/144603050/dceb9d27-e535-40ee-9448-4d671bfa82e6">

**Comment by capnac** [comment]
I could find where `screens.KSscreen.kt` is but, still it is recognized as unresolved reference unless your documentation is missing a step here.

**Comment by Nikitae57** [comment]
Hi, @capnac! Could you give us more context, please? Are you going through our tutorial? If so, try givin gradle sync a go. After that depdendencies should be configured. 
You could find more info about KScreen type [here](https://kasperskylab.github.io/Kaspresso/en/Wiki/Page_object_in_Kaspresso/#what-is-a-page-object-pattern)

**Comment by Nikitae57** [comment]
If you still expreience troubles, please, reopen
