### ISSUE TITLE
Грам.ошибки в тексте

### ISSUE THREAD

**Issue by elyana29** [KasperskyLab/Kaspresso#579]
В уроке 3 мелкие опечатки:  
1. "Благодаря **нему** можно находить id элементов интерфейса... "  - "Благодаря ему" 

2. "Для того, чтобы перед тестом была запущена какая-то активити, **ножно** добавить следующие строки"  - "нужно"

**Comment by AzamatCherchesov** [comment]
Thank you for your request
Mistakes were fixed in the #585
