### ISSUE TITLE
Туториал. Урок 4 "Выполнение adb-команд". Команда "adbServer.performShell("pm list packages")" падает "with timeout exception"

### ISSUE THREAD

**Issue by Paiper147** [KasperskyLab/Kaspresso#582]
**Describe the bug**
https://kasperskylab.github.io/Kaspresso/ru/Tutorial/Working_with_adb/#adb_1
 Урок 4 "Выполнение adb-команд"

В уроке приведена одна из команд
val packages = **adbServer.performShell("pm list packages")**
Assert.assertTrue(device.targetContext.packageName in packages.first())

Однако при попытке её выполнить, в логах теста выводится:
"com.kaspersky.kaspresso.internal.exceptions.AdbServerException:
AdbServer. The command=pm list packages was performed with timeout exception."
![image](https://github.com/KasperskyLab/Kaspresso/assets/55734705/8310b3b8-2d12-4d99-9df7-f8590c539300)

В консоле выводится:
INFO 26/09/2023 11:59:52.833  desktop=Desktop-21720 device=emulator-5554   message: The received command to execute: AdbCommand(body=shell pm list packages)
INFO 26/09/2023 12:01:52.843  desktop=Desktop-21720 device=emulator-5554   message: The executed command: AdbCommand(body=shell pm list packages). The result: CommandResult(status=TIMEOUT, description=Command execution timeout (120 sec) overhead, serviceInfo=The command was executed on desktop=Desktop-21720)
![image](https://github.com/KasperskyLab/Kaspresso/assets/55734705/6560e89f-f12b-4bc1-9377-2006d2da36fe)

Код, указанный выше, был запущен из ветки "TECH-tutorial-results", класс AdbTest.kt.
Также есть класс DeviceServerSampleTest.kt , в котором приведён аналогичный тест
val command = "pm list packages **${device.targetContext.packageName}**"
val result = adbServer.performShell(command)
assertTrue("package:${device.targetContext.packageName}" in result.first())
Данный код выполняется **БЕЗ ошибок**

![image](https://github.com/KasperskyLab/Kaspresso/assets/55734705/5855d832-321f-4dcf-af47-6a2a0b1ad31a)

**Comment by Nikitae57** [comment]
Sorry, could not reproduce. Please, try out the newest kaspresso version and adb-server-desktop.jar
