### ISSUE TITLE
Impossible to find some texts with RecyclerView

### ISSUE THREAD

**Issue by Pirokar** [KasperskyLab/Kaspresso#583]
**Describe the bug**
I have RecyclerView with several holders. 

It's impossible to find the text here (see screenshot section) with 
```kotlin
childAt<ChatMainScreen.ChatRecyclerItem>(3) {
    hasDescendant { containsText("Добро пожаловать в наш чат") }
}
``` 

or with:

```kotlin
childAt<ChatMainScreen.ChatRecyclerItem>(3) {
    itemText.containsText("Добро пожаловать в наш чат")
}
``` 

My screen is:

```kotlin
object ChatMainScreen : KScreen<ChatMainScreen>() {
    override val layoutId: Int = R.layout.ecc_fragment_chat
    override val viewClass: Class<*> = ChatFragment::class.java

  // ...

    val recyclerView = KRecyclerView(
        builder = { withId(R.id.chatItemsRecycler) },
        itemTypeBuilder = { itemType(ChatMainScreen::ChatRecyclerItem) }
    )

    class ChatRecyclerItem(matcher: Matcher<View>) : KRecyclerItem<ChatRecyclerItem>(matcher) {
        val itemText = KTextView(matcher) { withId(R.id.text) }
        val itemTime = KTextView(matcher) { withId(R.id.timeStamp) }
    }
}
``` 

Layout also has this TextView with "text" id.

**Expected behavior**
This text is possible to find.

**Screenshots**
![image](https://github.com/KasperskyLab/Kaspresso/assets/12714628/515922a9-3f2a-4877-bb8d-cba14fbea07d)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 (emulator)
 - OS: Api 33

**Kaspresso version**
1.5.3

**Comment by alekseyp555** [comment]
Approve this issue with recycler and child

**Comment by Nikitae57** [comment]
Hi, @Pirokar! Please, try this code:
 ```kotlin
childAt<ChatMainScreen.ChatRecyclerItem>(3) { // make sure, you use the right index
    itemText { 
        hasText("Добро пожаловать в наш чат!") 
    }
}
```
If this doesn't work, please, reopen the issue and attach test artifacts, the more - the better: exception, logs, views dump etc
