### ISSUE TITLE
Update Kaspresso version in README and Docs

### ISSUE THREAD

**Issue by avfe** [KasperskyLab/Kaspresso#605]
These files contain the wrong version of Kaspresso:

README.md - https://github.com/KasperskyLab/Kaspresso/blob/master/README.md
index.ru.md - https://github.com/KasperskyLab/Kaspresso/blob/master/docs/index.ru.md
index.en.md - https://github.com/KasperskyLab/Kaspresso/blob/master/docs/index.en.md
index.md - https://github.com/KasperskyLab/Kaspresso/blob/master/samples/kaspresso-sample/src/main/assets/index.html

Please, change 'com.kaspersky.android-components:kaspresso:1.0.1-support' to 'com.kaspersky.android-components:kaspresso:1.5.3'

**Comment by AzamatCherchesov** [comment]
Fixed in PR #606  https://github.com/KasperskyLab/Kaspresso/pull/606
