### ISSUE TITLE
New version of adbserver-dekstop.jar doesnt work and requires modern version

### ISSUE THREAD

**Issue by podkovyrova** [KasperskyLab/Kaspresso#624]
**Describe the bug**
New version of adbserver-dekstop.jar doesnt work and requires modern version. Tests failed with exception:
There was some problem inside a Socket creation process or during a Socket connection. The most possible reason is using of old version of 'adbserver-desktop.jar (desktop.jar)'. Please, use the most modern version of 'adbserver-desktop.jar' located in https://github.com/KasperskyLab/Kaspresso/tree/master/artifacts., serviceInfo=null

**To Reproduce**
1. Run CI autotests using adb-server with new adb-server that we get from repository (wget https://github.com/KasperskyLab/Kaspresso/blob/master/artifacts/adbserver-desktop.jar && java -jar adbserver-desktop.jar)
2. See console output from virtual machine

**Expected behavior**
Running adb-server and tests. 

**Desktop:**
- linux_x86_64

**Additional context**
The problem appeared after updating adbserver-desktop.jar 22 Jan.

**Comment by Nikitae57** [comment]
Hi, @podkovyrova! Please, update to kaspresso v1.5.4 or use the old ADB server [binary](https://github.com/KasperskyLab/Kaspresso/blob/v.1.5.3/artifacts/adbserver-desktop.jar)
