### ISSUE TITLE
Реализовать удобный и понятный API для ожидания появления View или его состояния

### ISSUE THREAD

**Issue by almaz010891** [KasperskyLab/Kaspresso#64]
В Telegram-чате Kaspresso&AdbServer support [RU] обсуждали идею удобного и интуитивно понятного API для ситуаций, когда необходимо ожидать появления View в иерархии (аналог Espresso Idling Resource).

Проблематика: сейчас это можно реализовать с помощью flakySafely + метода isVisible(), но это неудобно (нужно оборачивать в before{ }.after{ }.run{ }), неочевидно и решает не совсем ту задачу, о которой я пишу.

Хотелось бы иметь возможность явно указать, что View может изначально не быть в иерархии (ViewNotFoundException). Какие варианты мне видятся наиболее лаконичными (в порядке убывания):

1. Использование аннотации (**@Idling, @Idle, @IdlingResource**) при инициализации KView. Например:
```
class MainActivityScreen : Screen<MainActivityScreen>() {    
    @Idling(maxWaitMillis = 60_000)
    val moreBtn = KButton {withId(R.id.btn_more)}
}
```

2. С помощью дополнительного метода в самом тесте, например, wait(maxWaitMillis = 60_000):
```
@Test
    fun mainActivityTest() {
        mainActivityScreen{
            moreBtn {
                wait(maxWaitMillis = 60_000)
                click()
            }
        }
    }
```

Второй вариант делает чтение теста более понятным (т.к. аннотация находится в другом классе, ее не будет видно из класса с тестами, в отличие от метода wait()). Можно конечно заморочиться и для аннотированных объектов генерировать объект с именем moreBtnIdle и в тесте использовать уже его, но это полет фантазии уже)

Также часто возникают ситуации, когда нужно дождаться состояния уже существующего в иерархии View (например, дождаться состояния кнопки isEnabled, а затем кликнуть по ней).

Пусть это будет метод waitFor{} (waitForState{}, waitState{}) в который можно поместить assert-ы которые доступны только для объявленного KView (в данном случае KButton). Также должна быть возможность указать кастомные matcher-ы/assert-ы

Применив идею на примере выше, было бы отлично писать код в следующем стиле:
```
@Test
    fun mainActivityTest() {
        mainActivityScreen{
            moreBtn {
               wait(maxWaitMillis = 60_000) //или аннотация @Idling
               waitFor(maxWaitMillis = 60_000) {
                      isEnabled()
               }
               click()
               waitFor(maxWaitMillis = 60_000) {
                      withText(R.string.new_btn_text)
               }
            }
        }
    }
```

В результате тест можно было трактовать так: ждать появления в иерархии moreBtn максимум 60 секунд. После того, как кнопка появится, ждать состояния isEnabled и после этого выполнить по ней клик, после чего дождаться текста R.string.new_btn_text

Был бы очень рад такому API. Возможно, вы разовьете идею и придумаете еще более элегантное решение. Заранее спасибо)

**Comment by RuslanMingaliev** [comment]
@matzuk @eakurnikov Давайте обсудим

**Comment by matzuk** [comment]
@RuslanMingaliev предлагаю еще раз обсудить

**Comment by RuslanMingaliev** [comment]
@almaz010891, привет! 

Выделил из issue две проблемы и предложения их решения:
1. Нет механизма, который бы позволил дождаться момента, когда кнопка появится в иерархии и выполнить с ней какое-либо действие
2. Нет механизма, который бы позволил дождаться определенного состояния кнопки и выполнить с ней действие. 

Обе проблемы можно решить, используя механизм [flakySafely](https://github.com/KasperskyLab/Kaspresso/blob/master/kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/flakysafety/algorithm/FlakySafetyAlgorithm.kt). Например, 

```kotlin
@Test
fun sample() = run {
    MainActivityScreen {
        flakySafely(timeoutMs = 60_000, intervalMs = 500, allowedExceptions(...)) {
            moreBtn {
                isVisible()
                isEnabled()
                click()
                withText(...)
            }
        }
    }
}
```
метод `flakySafely` принимает в себя (опционально) следующие параметры:
`timeoutMs` - максимальное время для выполнения действия
`intervalMs` - промежуток времени между выполнением действия
`allowedException` - список разрешенных исключений, которые будут подавляться при выполнении действия и перезапускать его через интервал. 

Таким образом, в примере, который я привел выше, будет пытаться выполниться проверка на видимость кнопки, затем на её доступность (enabled), и когда оба условия выполнятся, произойдет клик на кнопку и проверка withText(). То есть этот код идентичен примеру из issue. withText можно вынести в отдельный блок flakySafely, если не нужно при фейле заново проверять на видимость, доступность и делать клик. Ну и если нужного исключения нет в [списке](https://github.com/KasperskyLab/Kaspresso/blob/master/kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/params/FlakySafetyParams.kt) стандартных исключений (a `ViewNotFoundException` там нет), то надо его добавить в allowedExceptions.

Если не очень удобно делать такую проверку в тесте, и надо унести в `Screen`, в котором нет `BaseTestContext`, то можно сделать так:

```kotlin
object MainActivityScreen {
    val moreBtn = KButton { withId(R.id.btn_more) }

    fun BaseTestContext.waitForButtonVisibleState(timeoutMs: Long) {
        flakySafely(timeoutMs = timeoutMs) {
            moreBtn.isVisible()
        } 
    }
} 
```

Ну и вызывать в тесте таким образом:

```kotlin
@Test
fun sample() = run {
    MainActivityScreen {
        waitForButtonVisibleState(timeoutMs = 5_000) 
        moreBtn.click()
    }
}
```

Согласен, что по названию метода `flakySafely` может быть не очевидно, как он на самом деле работает. @almaz010891, @matzuk, предлагайте названия, можем переименовать, а `flakySafely` оставить для обратной совместимости и сделать deprecated

**Comment by RuslanMingaliev** [comment]
Пока закрываю issue. @almaz010891 переоткрой, если ещё остались вопросы, обсудим. Можно даже созвониться.
