### ISSUE TITLE
Problems with screenshotting before/after a test

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#74]
**Stacktrace**:
E/UiDevice: failed to save screen shot to file
 java.io.FileNotFoundException: /storage/emulated/0/screenshots/com.kaspersky.kaspressample.simple_tests.SimpleTest/test/1578485958639_SimpleTest_step_1.png: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:496)

**Additional information**:
[screenshot with the error](https://habrastorage.org/webt/yo/vo/83/yovo83nze_jrmwcbxqosyved-ee.png)

**Comment by matzuk** [comment]
close #92

**Comment by matzuk** [comment]
1. Add permissions in a test:
```
@get:Rule
    val runtimePermissionRule: GrantPermissionRule = GrantPermissionRule.grant(
        Manifest.permission.WRITE_EXTERNAL_STORAGE,
        Manifest.permission.READ_EXTERNAL_STORAGE
    )
```
2. Clean/rebuild project
3. Remove target application in your emulator/device

**Comment by fidel-TAB** [comment]
Tried this, I still get the error. Am I missing something?
