### ISSUE TITLE
Make adbServer and kaspresso version dependant

### ISSUE THREAD

**Issue by priomino** [KasperskyLab/Kaspresso#77]
Force kaspresso check version of adb server for compatibility.
If not compatible then report current and compatible version and fail test on first request to adb server.

**Comment by priomino** [comment]
Writing this because sometimes both components are not in sync and cause some problems.
This is reported because some dev asked me how to solve this problem.

**Comment by matzuk** [comment]
@RuslanMingaliev  Have a look at this issue

**Comment by RuslanMingaliev** [comment]
Duplicates #132
