### ISSUE TITLE
[Kautomator] Добавить оставшиеся обертки над Android компонентами и написать сэмплы

### ISSUE THREAD

**Issue by RuslanMingaliev** [KasperskyLab/Kaspresso#87]
Уже есть большинство оберток и примеров использования. Нужно добавить оставшиеся и написать на них тесты.

**Comment by RuslanMingaliev** [comment]
@matzuk 5 февраля

**Comment by AzamatCherchesov** [comment]
@RuslanMingaliev  Hi! =)
Could you provide more information and status? What elements are not yet wrapped and added to the samples? 
@matzuk can you join this discussion too?)

**Comment by AzamatCherchesov** [comment]
No additional information provided
I close this issue

If relevant information appears, the task will be reopened
