### ISSUE TITLE
DocLocScreenshotTestCase does not save failure screenshots

### ISSUE THREAD

**Issue by aartikov** [KasperskyLab/Kaspresso#96]
Steps to reproduce:

1.  Change `kaspressample.docloc_tests.ScreenshotSampleTest` to make it failing.
2. Run the test.
3. Open "sdcard/screenshots/en" in Device File Explorer.

Expected behavior: "fails" directory contains a failure screenshot.

Actual behavior: "fails" directory is empty. Logcat has `java.lang.IllegalArgumentException: Could not find test class!`

Tested on Emulator API 26, x86_64.

**Comment by matzuk** [comment]
@aartikov Hi!
Is the issue actual?

**Comment by AzamatCherchesov** [comment]
@aartikov Hi!
Thanks for your issue.
Is the issue actual?
