### ISSUE TITLE
Wiki. How to write autotests. Improvements

### ISSUE THREAD

**Issue by matzuk** [KasperskyLab/Kaspresso#97]
Possible additional topics:
1. Who is responsible for pushing the entire autotests process.
2. The strategy of how to execute autotests. E2E, functional tests. What about tests in PR. 
Don't forget this class - ClassificatorAnnotations.kt.

**Comment by AzamatCherchesov** [comment]
great idea

I close this issue as a duplicate to this one https://github.com/KasperskyLab/Kaspresso/issues/491

In this issue we will collect all the wishes for documentation
